
[functions.get-document-for-signing]
enabled = true
verify_jwt = true
import_map = "./functions/get-document-for-signing/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/get-document-for-signing/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/get-document-for-signing/*.html" ]

[functions.generate-signed-pdf]
enabled = true
verify_jwt = true
import_map = "./functions/generate-signed-pdf/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/generate-signed-pdf/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/generate-signed-pdf/*.html" ]

[functions.upload-signed-pdf]
enabled = true
verify_jwt = true
import_map = "./functions/upload-signed-pdf/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/upload-signed-pdf/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/upload-signed-pdf/*.html" ]
